#!/bin/bash

ssh -i "LAMP.pem" ubuntu@ec2-44-220-137-21.compute-1.amazonaws.com
# to change the permissions to the key use:
 chmod 400 LAMP.pem

# INSTALLING APACHE AND UPDATING THE FIREWALL
# Update and Ugrade packages in the package manager
sudo apt update
sudo apt upgrade
sudo apt install apache2 
# Reboot the system
sudo reboot
# Check if apache2 is running
sudo systemctl start apache2
sudo systemctl status apache2
sudo systemctl enable apache2

# Connect to the instance using: 44.220.137.21.
apache_display_working.PNG

# INSTALLING MYSQL
sudo apt install mysql-server
sudo mysql_secure_installationsudo mysql
# log into mysql console
sudo mysql
# set password for the root user
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'Password.1';
exit;
# run security script which removes insecure defaults
sudo mysql_secure_installation
# log into Mysql console
mysql root -p
# create new user
mysql -u root -p

# INSTALLING PHP
sudo apt install php libapache2-mod-php php-mysql

php -v

# CREATING A VIRTUAL HOST FOR WEBSITE USING APACHE

mkdir /var/www/html/LAMPstack
chown -R $USER:$USER /var/www/html/LAMPstack
# create a sample page or info.php page
vi /var/www/html/LAMPstack/info.php
# input 
<?php
phpinfo();
?>
ls /var/www/html/LAMPstack

# create and configuration file in apache's sites-available
sudo vi /etc/apache2/sites-available/LAMPstack.conf
sudo vi /var /www/html/LAMPstack
# input the following:
<VirtualHost *:80>
ServerName LAMPstack
ServerAlias www.LAMPstack
ServerAdmin webmaster@localhost
DocumentRoot /var/www/LAMPstack
ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>

sudo ls /etc/apache2/sites-available
a2ensite LAMPstack.conf
sudo a2dissite 000-default
sudo apache2ctl configtest
sudo systemctl reload apache2
virtual_server.PNG
# Enable PHP on the Website
sudo vi /etc/apache2/mods-enabled/dir.conf
# input the following:
sudo systemctl reload apache2
# Create index.php inside custom folder
sudo vi /var/www/Project_Lamp/index.php
# Input this:
<?php
phpinfo();
php_display.PNG
sudo rm /var/www/Project_Lamp/index.php


