#!/bin/bash

# update packages
sudo apt update
# upgrade packages
sudo apt upgrade

# use this to check if node version is supported if not go to website to get latest version
curl -fsSL https://deb.nodesource.com/setup_24.x | sudo -E bash -
# Install Node js on ubuntu
sudo apt install nodejs -u
node -v
npm -v

# create a folder
mkdir todo
cd todo
npm init
npm -v
# use this immediately after npm init
todo, todo, steghub todo app, index.js, psalmist
ls
cat package.json

# Install ExpressJs and dotenv
npm install express
sudo npm Install dotenv

# create index.js file
vi index.js:
const express = require('express');
require('dotenv').config();

const app = express();

const port = process.env.PORT || 5000;

app.use((req, res, next) => {
res.header("Access-Control-Allow-Origin", "\*");
res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-type, Accept")
next();
});

app.use((req, res, next) => {
res.send('Welcome to Express');
});
app.listen(port, () => {
console.log(`Server running on port ${port}`)
});

node index.js express welcomepage.png
ls node_modules

# create a folder for standard request
mkdir routes
cd routes
vi api.js
const express = require ('express');
const router = express.Router();

router.get('/todos', (req, res, next) => {

});

router.post('/todos', (req, res, next) => {

});

router.delete('/todos/:id', (req, res, next) => {

});

module.exports = router;

cat api.js

# Install mongoose and create a model for todo
cd ..
npm install mongoose
npm list mongoose
mkdir models && cd models && touch todo.js
cd models
vi todo.js
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

//create Schema for todo
const TodoSchema = new schema({
action: {
type: string,
required: [true, 'The todo text field is required']
}
})

//create model for todo
const todo mongoose.model('todo', TodoSchema);

module.export = Todo;

# Update the api.js file to include the model and implement the CRUD operations
cd ../routes 
vi api.js

# delete api.js file content and input the following:
const express = require('express');
const router = express.Router();
const Todo = require('../models/todo');

router.get('/todos', (req, res, next) => {

//this will return all the data, exposing only the id and action field to the client
Todo.find({}, 'action')
.then(data => res.jason(data))
.catch(next)
});

router.post('/todos', (req, res, next) => {
if(req.body.action){
Todo.create(req.body)
.then(data => req.jason(data))
.catch(next)
}else {
res.jason({
error: "The input field is empty"
})
}
})

router.delete('/todos/:id', (req, res, next) => {
Todo.findOneAndDelete({"_id": req.params.id})
.then(data => res.jason(data))
.catch(next)
})

module.exports = router

# create mongoDB database on cloud ans get it connected
# create a cluster on the mongoDB cloud
# click the free tier and create a cluster
# create deployment
# after deploying cluster, configure network access for mongoDB
# create the dotenv file inside todo folder and input:
mongodb+srv://<db_username>:CXFqMXX31XS3tf2l@cluster0.cijevc3.mongodb.net/?appName=Cluster0
cd .. && vi .env
mongodb+srv://bostec29_db_user:OlsyEnYOabLax5jz@cluster0.4zfi4lm.mongodb.net

# edit the index.js file and input the following:
vi index.js
const express = require('express');
const bodyParser = require('body-parser');
const mongoose = require('mongoose');
const routes = require('./routes/api');
require('dotenv').config();

const app = express();

const port = process.env.PORT || 5000;

// Middleware
app.use(bodyParser.json());

// CORS
app.use((req, res, next) => {
    res.header("Access-Control-Allow-Origin", "*");
    res.header(
        "Access-Control-Allow-Headers",
        "Origin, X-Requested-With, Content-Type, Accept"
    );
    next();
});

// Connect to MongoDB
mongoose
    .connect(process.env.DB)
    .then(() => console.log("Database connected successfully"))
    .catch((err) => console.error("Database connection error:", err));

// Routes
app.use('/api', routes);

// Error handling middleware
app.use((err, req, res, next) => {
    console.error(err.stack);

    res.status(err.status || 500).json({
        success: false,
        message: err.message || "Internal Server Error"
    });
});

// Start server
app.listen(port, () => {
    console.log(`Server running on port ${port}`);
});

# create a .env file and input the following:
DB=mongodb+srv://bostec29_db_user:OlsyEnYOabLax5jz@cluster0.4zfi4lm.mongodb.net
node index.js

# test the api using postman
# from the Header choose content type and select application/json
# under Database and Network select IP access list to add another IP address to allow access to the database