#!/bin/bash

# update packages
sudo apt update
# upgrade packages
sudo apt upgrade

# use this to check if node version is supported if not go to website to get latest version
curl -fsSL https://deb.nodesource.com/setup_24.x | sudo -E bash -
# Install Node js on ubuntu
sudo apt install nodejs -u
node -v
npm -v

# create a folder
mkdir todo
cd todo
npm init
npm -v
# use this immediately after npm init
todo, todo, steghub todo app, index.js, psalmist
ls
cat package.json

# Install ExpressJs and dotenv
npm install express
sudo npm Install dotenv

# create index.js file
vi index.js:
const express = require('express');
require('dotenv').config();

const app = express();

const port = process.env.PORT || 5000;

app.use((req, res, next) => {
res.header("Access-Control-Allow-Origin", "\*");
res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-type, Accept")
next();
});

app.use((req, res, next) => {
res.send('Welcome to Express');
});
app.listen(port, () => {
console.log(`Server running on port ${port}`)
});

node index.js express welcomepage.png
ls node_modules

# create a folder for standard request
mkdir routes
cd routes
vi api.js
const express = require ('express');
const router = express.Router();

router.get('/todos', (req, res, next) => {

});

router.post('/todos', (req, res, next) => {

});

router.delete('/todos/:id', (req, res, next) => {

});

module.exports = router;

cat api.js

# Install mongoose and create a model for todo
cd ..
npm install mongoose
npm list mongoose
mkdir models && cd models && touch todo.js
cd models
vi todo.js
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

//create Schema for todo
const TodoSchema = new schema({
action: {
type: string,
required: [true, 'The todo text field is required']
}
})

//create model for todo
const todo mongoose.model('todo', TodoSchema);

module.export = Todo;

# Update the api.js file to include the model and implement the CRUD operations
cd ../routes 
vi api.js

# delete api.js file content and input the following:
const express = require('express');
const router = express.Router();
const Todo = require('../models/todo');

router.get('/todos', (req, res, next) => {

//this will return all the data, exposing only the id and action field to the client
Todo.find({}, 'action')
.then(data => res.jason(data))
.catch(next)
});

router.post('/todos', (req, res, next) => {
if(req.body.action){
Todo.create(req.body)
.then(data => req.jason(data))
.catch(next)
}else {
res.jason({
error: "The input field is empty"
})
}
})

router.delete('/todos/:id', (req, res, next) => {
Todo.findOneAndDelete({"_id": req.params.id})
.then(data => res.jason(data))
.catch(next)
})

module.exports = router

# create mongoDB database on cloud ans get it connected
# create a cluster on the mongoDB cloud
# click the free tier and create a cluster
# create deployment
# after deploying cluster, configure network access for mongoDB
# create the dotenv file inside todo folder and input:
mongodb+srv://<db_username>:CXFqMXX31XS3tf2l@cluster0.cijevc3.mongodb.net/?appName=Cluster0
cd .. && vi .env
mongodb+srv://bostec29_db_user:OlsyEnYOabLax5jz@cluster0.4zfi4lm.mongodb.net

# edit the index.js file and input the following:
vi index.js
const express = require('express');
const bodyParser = require('body-parser');
const mongoose = require('mongoose');
const routes = require('./routes/api');
require('dotenv').config();

const app = express();

const port = process.env.PORT || 5000;

// Middleware
app.use(bodyParser.json());

// CORS
app.use((req, res, next) => {
    res.header("Access-Control-Allow-Origin", "*");
    res.header(
        "Access-Control-Allow-Headers",
        "Origin, X-Requested-With, Content-Type, Accept"
    );
    next();
});

// Connect to MongoDB
mongoose
    .connect(process.env.DB)
    .then(() => console.log("Database connected successfully"))
    .catch((err) => console.error("Database connection error:", err));

// Routes
app.use('/api', routes);

// Error handling middleware
app.use((err, req, res, next) => {
    console.error(err.stack);

    res.status(err.status || 500).json({
        success: false,
        message: err.message || "Internal Server Error"
    });
});

// Start server
app.listen(port, () => {
    console.log(`Server running on port ${port}`);
});

# create a .env file and input the following:
DB=mongodb+srv://bostec29_db_user:OlsyEnYOabLax5jz@cluster0.4zfi4lm.mongodb.net
node index.js

# test the api using postman
# from the Header choose content type and select application/json
# in the mongodb under Database and Network select IP access list to add another IP address to allow access to the database
using postman.png

# Frontend creating react app. run the following command in the todo folder
npx create-react-app client
# when the react client folder is created delete, then use vite to create new react app
rm -rf client
npm create vite@latest client
# select react as the framework and javascript as the language
ls client

# install concurrently and nodemon to run both backend and frontend together
npm install concurrently nodemon --save-dev
# edit the package.json file in the todo folder to include the following scripts:
{
  "name": "todo",
  "version": "1.0.0",
  "description": "Steghub Todo Application",
  "main": "index.js",
  "scripts": {
    "start": "node index.js",
    "start-watch": "nodemon index.js",
    "dev": "concurrently \"npm run start-watch\" \"cd client && npm run dev\""
  },
  "author": "psalms",
  "license": "ISC",
  "dependencies": {
    "dotenv": "^17.3.1",
    "express": "^5.2.1",
    "mongoose": "^9.2.3"
  },
  "devDependencies": {
    "concurrently": "^9.2.1",
    "nodemon": "^3.1.14"
  }
}

cd client
vi package.json:
{
  "name": "client",
  "private": true,
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "lint": "oxlint",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^19.1.1",
    "react-dom": "^19.1.1"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^5.1.0",
    "oxlint": "^1.71.0",
    "vite": "^7.1.3"
  }
}

cd ..
npm run dev

# create a react component for the todo app in the client/src folder
cd client 
cat src/main.jsx
cat src/App.jsx
vi vite.config.js : 
server: {
        port: 3000,}
cd ..
npm run dev
ctrl c
cd client/src
mkdir components
cd components
touch Input.js ListTodo.js Todo.js
vi Input.js:

import React, { Component } from 'react';
import axios from 'axios';

class Input extends Component {

state = {
action: ""
}

addTodo = () => {
const task = {action: this.state.action}

    if(task.action && task.action.length > 0){
      axios.post('/api/todos', task)
        .then(res => {
          if(res.data){
            this.props.getTodos();
            this.setState({action: ""})
          }
        })
        .catch(err => console.log(err))
    }else {
      console.log('input field required')
    }

}

handleChange = (e) => {
this.setState({
action: e.target.value
})
}

render() {
let { action } = this.state;
return (
<div>
<input type="text" onChange={this.handleChange} value={action} />
<button onClick={this.addTodo}>add todo</button>
</div>
)
}
}

export default Input

cd ..
cd ..
npm install axios
cd src/components
vi ListTodo.js
import React from 'react';

const ListTodo = ({ todos, deleteTodo }) => {

return (
<ul>
{
todos &&
todos.length > 0 ?
(
todos.map(todo => {
return (
<li key={todo._id} onClick={() => deleteTodo(todo._id)}>{todo.action}</li>
)
})
)
:
(
<li>No todo(s) left</li>
)
}
</ul>
)
}

export default ListTodo

vi Todo.js

import React, {Component} from 'react';
import axios from 'axios';

import Input from './Input';
import ListTodo from './ListTodo';

class Todo extends Component {

state = {
todos: []
}

componentDidMount(){
this.getTodos();
}

getTodos = () => {
axios.get('/api/todos')
.then(res => {
if(res.data){
this.setState({
todos: res.data
})
}
})
.catch(err => console.log(err))
}

deleteTodo = (id) => {

    axios.delete(`/api/todos/${id}`)
      .then(res => {
        if(res.data){
          this.getTodos()
        }
      })
      .catch(err => console.log(err))

}

render() {
let { todos } = this.state;

    return(
      <div>
        <h1>My Todo(s)</h1>
        <Input getTodos={this.getTodos}/>
        <ListTodo todos={todos} deleteTodo={this.deleteTodo}/>
      </div>
    )

}
}

export default Todo;

# go back to the src folder and edit App.js and App.css to include the following:

cd ..

vi App.js:
import React from 'react';

import Todo from './components/Todo';
import './App.css';

const App = () => {
return (
<div className="App">
<Todo />
</div>
);
}

export default App;

vi App.css:
.App {
text-align: center;
font-size: calc(10px + 2vmin);
width: 60%;
margin-left: auto;
margin-right: auto;
}

input {
height: 40px;
width: 50%;
border: none;
border-bottom: 2px #101113 solid;
background: none;
font-size: 1.5rem;
color: #787a80;
}

input:focus {
outline: none;
}

button {
width: 25%;
height: 45px;
border: none;
margin-left: 10px;
font-size: 25px;
background: #101113;
border-radius: 5px;
color: #787a80;
cursor: pointer;
}

button:focus {
outline: none;
}

ul {
list-style: none;
text-align: left;
padding: 15px;
background: #171a1f;
border-radius: 5px;
}

li {
padding: 15px;
font-size: 1.5rem;
margin-bottom: 15px;
background: #282c34;
border-radius: 5px;
overflow-wrap: break-word;
cursor: pointer;
}

@media only screen and (min-width: 300px) {
.App {
width: 80%;
}

input {
width: 100%
}

button {
width: 100%;
margin-top: 15px;
margin-left: 0;
}
}

@media only screen and (min-width: 640px) {
.App {
width: 60%;
}

input {
width: 50%;
}

button {
width: 30%;
margin-left: 10px;
margin-top: 0;
}
}

vi index.css:
body {
margin: 0;
padding: 0;
font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen",
"Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue",
sans-serif;
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
box-sizing: border-box;
background-color: #282c34;
color: #787a80;
}

code {
font-family: source-code-pro, Menlo, Monaco, Consolas, "Courier New",
monospace;
}

cd ../..
npm run dev
cd client/src/components
mv Input.js Input.jsx
mv ListTodo.js ListTodo.jsx
mv Todo.js Todo.jsx
cd ../../..
cd client
vi package.json:

{
  "name": "client",
  "private": true,
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "lint": "oxlint",
    "preview": "vite preview"
  },
  "dependencies": {
    "axios": "^1.6.5",
    "react": "^19.1.1",
    "react-dom": "^19.1.1"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^5.1.0",
    "oxlint": "^1.71.0",
    "vite": "^7.1.3"
  }
}

# open the index.css file and add the following code to style the app:
body {
margin: 0;
padding: 0;
font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen",
"Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue",
sans-serif;
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
box-sizing: border-box;
background-color: #282c34;
color: #787a80;
}

code {
font-family: source-code-pro, Menlo, Monaco, Consolas, "Courier New",
monospace;
}

# return to the todo folder and run the app using the command:
cd ../..
npm run dev
